language: python
dist: xenial
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  # - "pypy"
services:
  - xvfb
before_install:
  - "export DISPLAY=:99.0"
cache: pip
# command to install dependencies
install:
  - pip install -U setuptools pytest
  - pip install Cython --install-option="--no-cython-compile"
  - pip install lxml
  - pip install --only-binary=numpy numpy
  - pip install .
# command to run tests
script: pytest test
